openapi: 3.0.0
info:
  title: Dr. Max IPF - Eshop / M2 API
  description: Dr.Max Eshop API provides comprehensive set of features for consumers
    whom realize CrossDock business integration as well as prepare new version of
    other processes
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/DrMax_BDC/CrossDock/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://{username}.gigantic-server.com:{port}/{basePath}
  description: The production API server
  variables:
    username:
      description: Test instance of DrMax Integration platform
      default: Test
    port:
      default: "8443"
      enum:
      - "8443"
      - "443"
    basePath:
      default: v1
paths:
  /eShop-services/api/v1/order/:
    post:
      tags:
      - Shop
      summary: Create Order
      description: Creates new order object, in case of _Reservation type_ is passed
        into pharmacy (Farmis instance). Order object already exists in EShop DB and
        it is passed as a request body of this call.
      operationId: CreateOrder
      parameters:
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: true
        schema:
          type: string
          example: application/json
      requestBody:
        description: 'Order Data '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
  /eShop-services/api/v1/order/{orderId}:
    get:
      tags:
      - Shop
      summary: Get Order
      description: Returns the order object from e-Shop DB. (For now, will be used
        for operations and monitoring purposes as well as for debugging of issues)
      operationId: GetOrder
      parameters:
      - name: orderId
        in: path
        description: Id of the order.
        required: true
        style: simple
        explode: false
        schema:
          type: number
          example: 123
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
    put:
      tags:
      - Shop
      summary: Update Order
      description: Method should change order object attributes values, there will
        be some restrictions in the future, depends on status in the order lifecycle.
        It is aimed for changing order attributes on POS side.
      operationId: UpdateOrder
      parameters:
      - name: orderId
        in: path
        description: Id of the order document.
        required: true
        style: simple
        explode: false
        schema:
          type: number
          example: 123
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              example:
                resultCode: true
                errorCode: OK
                errorDescription: OK.
    delete:
      tags:
      - Shop
      summary: Delete Order
      description: 'In Case of type: Reservation: Calls respective e-Shop and Farmis
        instance to delete the reservation objects in pharmacy. In Case of type: Order:
        destroy the persisted data about order, in future should be passed to other
        BackEnds'
      operationId: DeleteOrder
      parameters:
      - name: orderId
        in: path
        description: Id of the order.
        required: true
        style: simple
        explode: false
        schema:
          type: number
          example: 123
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              example:
                resultCode: true
                errorCode: OK
                errorDescription: OK.
  /eShop-services/api/v1/order/{orderId}/status:
    put:
      tags:
      - Shop
      summary: Update Order Status
      description: "OBSOLETE: Updates Order Status.\nIn case of Reservation Type:\
        \ \nReservation Status can be updated during reservation processing.\n- Reservation\
        \ Status has the value `Requested` when the reservation was created in EShop\
        \ and sent to respective Farmis instance via IPF.\n- Reservation Status can\
        \ be updated by Farmis. In this case, the reservation status value can be\
        \ updated to `PreparedForExpedition`, `Completed`, `Cancelled` or `InTrouble`.\n\
        - Reservation Status update can be updated by call centre when the reservation\
        \ has status `InTrouble`. In this case, the reservation status can be updated\
        \ to `Requested` or `Cancelled`.\nIn case of eShop Type:\nTODO:\nThe Order\
        \ life cycle should be described"
      operationId: UpdateOrderStatus
      parameters:
      - name: orderId
        in: path
        description: Id of the order. Primary key.
        required: true
        style: simple
        explode: false
        schema:
          type: number
          example: 123
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderStatusRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommonResponse'
              example:
                resultCode: true
                errorCode: OK
                errorDescription: OK.
  /stock/api/v1/stock/available-product:
    post:
      tags:
      - Stock
      summary: GetProductAvailability
      description: Returns returns availability of the list of products on list of
        warehouses. When list of warehouses isn't present, returns avalability for
        all warehauses where product is presented. So this approach covers all availabilyty
        requests.
      operationId: GetProductAvailability
      parameters:
      - name: Content-Type
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductAvailabilityReq'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetproductavailabilityResponse'
components:
  schemas:
    CommonResponse:
      title: CommonResponse
      required:
      - resultCode
      type: object
      properties:
        resultCode:
          type: boolean
          description: 'Result code. True in case of success, false in case of error.
            Example: `true`.'
          example: true
        errorCode:
          type: string
          description: 'Error code. Short string with unique value. Examples: `OK`,
            `IPF0001`.'
          example: OK
        errorDescription:
          type: string
          description: 'Error description. It provides information about the reason
            of the error. Examples: `OK.`, `Internal error.`.'
          example: OK.
      example:
        resultCode: true
        errorCode: OK
        errorDescription: OK.
    AvailabilityType:
      title: availabilityType
      type: string
      example: Stock
      enum:
      - Stock
      - CrossDock
    Order:
      title: Order
      required:
      - dateTimeCreated
      - dateTimeReservationEnd
      - orderId
      - orderItems
      - totalDiscount
      - totalPrice
      - totalRounding
      - totalVAT
      - typeOfOrder
      type: object
      properties:
        typeOfOrder:
          $ref: '#/components/schemas/OrderType'
        status:
          $ref: '#/components/schemas/OrderStatus'
        eshopInstanceName:
          type: string
          description: Name of the e-Shop instance.
          example: magento2.CZE.production
        warehouseId:
          type: number
          description: Id of the warehouse.
          example: 55
        loggedUser:
          type: boolean
          description: Indicates, if the order has been filed by the user (1) or not
            (0).
          example: false
        dateTimeCreated:
          type: string
          description: Date and time when the order was created.
          example: 2018-10-01T16:29:08.000Z
        dateTimeReservationEnd:
          type: string
          description: Date and time when the order expires.
          example: 2018-10-01T16:29:08.000Z
        dateTimeLastUpdated:
          type: string
          description: Date and time when the order expires.
          example: 2018-10-01T16:29:08.000Z
        totalPrice:
          type: number
          description: Total price (incl. VAT).
          example: 575
        totalVAT:
          type: number
          description: Total VAT amount.
          example: 75
        totalDiscount:
          type: number
          description: Total discount (incl. VAT).
          example: 575
        totalRounding:
          type: number
          description: Total rounding amount (incl. VAT).
          example: 0
        customer:
          $ref: '#/components/schemas/Customer'
        addressItems:
          type: array
          description: Addresses for order
          items:
            $ref: '#/components/schemas/CustomerAddress'
        orderItems:
          type: array
          description: Order items.
          items:
            $ref: '#/components/schemas/OrderTreeItem'
        deliveryParams:
          $ref: '#/components/schemas/Delivery'
        eet:
          $ref: '#/components/schemas/EetData'
      description: Order main object
    OrderStatus:
      title: OrderStatus
      type: object
      properties:
        OrderStatusState:
          $ref: '#/components/schemas/OrderStatusState'
        OrderStatusReason:
          $ref: '#/components/schemas/OrderStatusReason'
    Delivery:
      title: Delivery data
      type: object
      properties:
        deliveryId:
          type: string
          description: Delivery service/package ID.
          example: "2589874563218"
        deliveryParams:
          type: boolean
          description: true = package to hand - morning delivery, false = package
            to hand afternoon delivery
          example: true
        deliveryPrice:
          $ref: '#/components/schemas/Price'
        packagingPrice:
          $ref: '#/components/schemas/Price'
    Price:
      title: Price object general
      type: object
      properties:
        price:
          type: number
          description: Price, amount
          example: 100.0
        vat:
          type: number
          description: VAT amount
          example: 21.0
        currency:
          type: string
          description: Curency of the price object, ISO 3alpha
          example: CZK
        discount:
          type: number
          description: Discount given to price
          example: 10.0
        rounding:
          type: number
          description: rounding related to price, rounding amount (incl. VAT).
          example: 0.23
    EetTaxRange:
      title: EET tax ranges
      type: array
      items:
        $ref: '#/components/schemas/EetTaxRange_inner'
    EetData:
      title: EET Data object
      required:
      - BKP
      - PKP
      - branchIdentification
      - cashRegisterEquipment
      - firstAttempt
      - messageUUID
      - receiptDate
      - receiptId
      - receiptTotalRevenue
      - revenueMode
      - sendDate
      - vatIdTaxpayer
      type: object
      properties:
        messageUUID:
          type: string
          description: Unique identification of the message UUID v4.
          example: d52c26ed-0c9d-4a12-9e84-4ee0a00b8611
        sendDate:
          type: string
          description: Date time of the EET message.
          example: 2018-10-01T16:29:08.000Z
        firstAttempt:
          type: boolean
          description: Identification of first try to send.
          example: true
        verification:
          type: boolean
          description: True = test message, False = real one by §18 ZoET meaning.
          example: false
        vatIdTaxpayer:
          type: string
          description: Vat ID of the taxpayer
          example: CZ213456789
        vatIdEntrustTaxpayer:
          type: string
          description: Vat ID of the Emtrust taxpayer
          example: CZ213456789
        branchIdentification:
          type: string
          description: Identification of the brach
          example: XYZ_321
        cashRegisterEquipment:
          type: string
          description: Identification of the cash register equipment according registration
            on the MF portal
          example: XYZ_321
        receiptId:
          type: string
          description: Identification of the cash register equipment according registration
            on the MF portal
          example: XYZ_321
        receiptDate:
          type: string
          description: Date time of the receipt.
          example: 2018-10-01T16:29:08.000Z
        receiptTotalRevenue:
          type: number
          description: Total revenue of the receipt.
          example: 12345.369
        vatRecapitulation:
          $ref: '#/components/schemas/EetTaxRange'
        postponedAmount:
          type: number
          description: Total revenue of the receipt.
          example: 12345.369
        postponedAmountPaid:
          type: number
          description: Total revenue of the receipt.
          example: 12345.369
        revenueMode:
          type: boolean
          description: Regime of the comunication.
          example: true
        PKP:
          type: string
          description: Signature code of the taxpayer .
          example: 123gt123yu456ui465uy654t465re65w4ertae
        BKP:
          type: string
          description: Security code of the taxpayer .
          example: 123gt123yu4dfg1016sr35g13sd5a3w56ui465
        FIK:
          type: string
          description: Security code of the transaction .
          example: 123gt123yu4dfg1016sr35g13sd5a3w56ui465
    OrderStatusState:
      title: OrderStatusState
      type: string
      example: Basketed
      enum:
      - Basketed
      - Validated
      - Locked
      - Backordered
      - Reserved
      - InTrouble
      - WMSQueued
      - Picking
      - WMSPackaging
      - WMSPacked
      - WMSProcessed
      - TransportWait
      - Transporting
      - Transported
      - ShipmentWait
      - Shipping
      - ReadyForPickup
      - Pickup
      - Delivered
      - Expired
      - ReturnTransportWait
      - ReturnTransporting
      - ReturnTransported
    OrderStatusReason:
      title: OrderStatusReason
      type: string
      example: AdminDuplicate
      enum:
      - Admin
      - Customer
      - WMS
      - POS
      - ERP
      - AdminDuplicate
    OrderType:
      title: OrderType
      type: string
      example: eShop
      enum:
      - eShop
      - Reservation
    TreeItemType:
      title: Type of the tree item.
      type: string
      example: item
      enum:
      - item
      - rule
    OrderStatusRequest:
      title: OrderStatusRequest
      required:
      - orderStatus
      type: object
      properties:
        orderStatus:
          $ref: '#/components/schemas/OrderStatus'
        note:
          type: string
          description: Note from the operator.
          example: OK
        userName:
          type: string
          description: User name of the operator (pharmacy, call centre).
          example: novak01
      example:
        orderStatus: PreparedForExpedition
        note: OK
        userName: novak01
    OrderTreeItem:
      title: OrderTreeItem
      required:
      - items
      - price
      - type
      type: object
      properties:
        type:
          $ref: '#/components/schemas/TreeItemType'
        couponOrderId:
          type: number
          description: Should be better described by e-shop
          example: 123456
        couponId:
          type: number
          description: Should be better described by e-shop
          example: 123456
        couponType:
          type: string
          description: Should be better described by e-shop
          example: A
        couponName:
          type: string
          description: Some sales rule name
          example: Christmas evil is coming
        totalDiscount:
          type: number
          description: Whole discount amount
          example: 10000
        maxCount:
          type: number
          description: Some counter
          example: 0
        price:
          type: number
          description: Price of the node
          example: 0
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        itemExtensions:
          type: array
          items:
            $ref: '#/components/schemas/ItemExtension'
    OrderItem:
      title: OrderItem
      required:
      - crossDock
      - orderItemId
      - price
      - productId
      - quantity
      - unitPrice
      - vatRate
      type: object
      properties:
        orderItemId:
          type: number
          description: Id of the item. Primary key.
          example: 12358
        productId:
          type: number
          description: Id of the product. Foreign key.
          example: 666111
        crossDock:
          type: boolean
          description: CrossDock Item identification, true = CrossDock, false = warehouse
            .
          example: true
        quantity:
          type: number
          description: Quantity of the product.
          example: 5
        unitPrice:
          type: number
          description: Unit price (incl. VAT) of the product.
          example: 25
        price:
          type: number
          description: Item price (incl. VAT) .
          example: 125
        vatRate:
          type: number
          description: VAT rate (percentage) of the product.
          example: 21
        discount:
          type: number
          description: Item discount
          example: 0
        bonusItem:
          type: boolean
          description: Identified bonus item in case of business special packages
          example: false
        bonusPrice:
          type: boolean
          description: Identified bonus price in case of business special packages
          example: false
        bonusRemoveable:
          type: boolean
          description: maening of this attribut should be better specified
          example: false
        bonusRemoved:
          type: boolean
          description: maening of this attribut should be better specified
          example: false
        productNote:
          type: string
          description: Product note (colour, size).
          example: Note.
    ItemExtension:
      title: itemExtension
      required:
      - key
      - value
      type: object
      properties:
        key:
          type: string
          description: Key name which determinate meaning of the value
          example: Some key name
        value:
          type: string
          description: Value paired with key
          example: 123456-call
        note:
          type: string
          description: Additional info related to key:value pair
          example: 'some note about 123456-call '
    AbstractCustomer:
      title: AbstractCustomer object
      required:
      - clientUID
      - firstName
      - lastName
      type: object
      properties:
        clientUID:
          type: number
          description: ID of the customer, Foreign key.
          example: 12598
        namePrefix:
          type: string
          description: Name prefix eg. titles.
          example: Ing.
        firstName:
          type: string
          description: First name of the customer.
          example: Jan
        lastName:
          type: string
          description: Last name of the customer.
          example: Novák
        middleName:
          type: string
          description: Middle name of the customer.
          example: Janovich
        nameSuffix:
          type: string
          description: Name suffix eg. titles.
          example: Csc.
        emailAddress:
          type: string
          description: Email Address of the customer.
          example: zakaznik@domena.cz
        phoneNumberPrefix:
          type: string
          description: Country prefix for phone number of the customer
          example: +420
        phoneNumber:
          type: number
          description: Phone number of the customer
          example: 123456789
      description: Object represents set of common data atributes for customer and
        customer address objects
    Customer:
      title: Customer
      required:
      - clientUID
      - firstName
      - lastName
      type: object
      properties:
        loyaltyCardId:
          type: string
          description: loyality Card ID  - DrMax to explain at least data format
          example: "123456789"
        identityId:
          type: string
          description: identity id
          example: AD123456789
        customerNote:
          type: string
          description: Note from the customer.
          example: Note from the customer.
      description: Object represents the Customer who will buy some drugs
      allOf:
      - $ref: '#/components/schemas/AbstractCustomer'
      - type: object
    CustomerAddress:
      title: Customer Address object
      required:
      - addressType
      - city
      - clientUID
      - firstName
      - lastName
      - postCode
      - shippingMethod
      - street
      type: object
      properties:
        addressType:
          type: string
          example: shipping
          enum:
          - shipping
          - billing
        shippingMethod:
          type: string
          example: messenger
          enum:
          - messenger
          - drugStore
        pickupId:
          type: string
          description: Id of the pickup type
          example: Lékárna
        countryId:
          type: string
          description: expected ISO alpha 3 country code as a integration standard
          example: CZE
        postCode:
          type: string
          description: ZIP
          example: "110000"
        city:
          type: string
          description: Address of the customer- town (village).
          example: Praha
        street:
          type: string
          description: Street name probably incl description like floor, flat num
            ....
          example: Praha
        descriptiveNumber:
          type: string
          description: Number of the building, the main one ....
          example: "3277"
        orientationNumber:
          type: string
          description: Number of the building, the helping one ....
          example: "6"
        companyName:
          type: string
          description: Company name in case of use with VAT identification.
          example: Jmeno firmy
        vatId:
          type: string
          description: VAT ID if applicable
          example: CZ365001458
        businessRegistration:
          type: string
          description: Business regitration , for CZECH means IČ0
          example: "365280047"
        regionId:
          type: number
          description: Id of the region
          example: 2
        regionCode:
          type: string
          description: Region code of the Address
          example: VM
        region:
          type: string
          description: Region of the Address
          example: Velka morava
      description: Object represents Address points of the customer who will buy some
        drugs
      allOf:
      - $ref: '#/components/schemas/AbstractCustomer'
      - type: object
    CreateOrderRequest:
      title: CreateOrderRequest
      required:
      - order
      - orderId
      type: object
      properties:
        orderId:
          type: number
          description: Id of the order. Primary key.
          example: 123
        order:
          $ref: '#/components/schemas/Order'
    ProductAvailabilityItem:
      title: ProductAvailabilityItem
      required:
      - productId
      type: object
      properties:
        sku:
          type: number
          description: Id of the product. Magento SKU (CZ market FarmisID)
          example: 666111
        availabilityOnWarehouse:
          type: array
          description: Present if product is available or zero in case that all stocks
            is ordered or reserved
          items:
            $ref: '#/components/schemas/WarehouseProductAvailabilityItem'
    WarehouseProductAvailabilityItem:
      title: WarehouseProductAvailabilityItem
      required:
      - availabilityType
      - availableQuantity
      - isUpToDate
      - providesReservation
      - warehouseId
      type: object
      properties:
        warehouseId:
          type: number
          description: Id of the warehouse, same as pharmacy ID in case of pharmacy
            warehouse.
          example: 666111
        availableQuantity:
          type: number
          description: Available quantity of the product at the warehouse. Available
            quantity equals Total quantity minus Frozen quantity minus Reserved/Ordered
            quantity.
          example: 6
        availabilityType:
          $ref: '#/components/schemas/AvailabilityType'
        providesReservation:
          type: boolean
          description: True, if the warehouse provides product reservations.
          example: true
        isUpToDate:
          type: boolean
          description: True, if the pharmacy is online and its stock item data is
            up-to-date.
          example: true
    ProductAvailabilityRes:
      title: ProductAvailabilityRes
      required:
      - availableStocks
      type: object
      properties:
        availableStocks:
          type: array
          description: Product availability on werhaouses
          items:
            $ref: '#/components/schemas/ProductAvailabilityItem'
    ListOfProduct:
      title: ListOfProduct
      required:
      - productId
      type: object
      properties:
        productId:
          type: array
          description: List of productIds
          items:
            type: string
    ListOfWarehouse:
      title: ListOfWarehouse
      required:
      - warehouseId
      type: object
      properties:
        warehouseId:
          type: array
          description: List of warehouseIds
          items:
            type: string
    ProductAvailabilityReq:
      title: ProductAvailabilityReq
      required:
      - product
      - warehouse
      type: object
      properties:
        product:
          type: array
          description: List of products for availability checking
          items:
            $ref: '#/components/schemas/ListOfProduct'
        warehouse:
          type: array
          description: List of products for availability checking, if not present
            whole availability will be returned
          items:
            $ref: '#/components/schemas/ListOfWarehouse'
      example:
        product:
        - productId:
          - 123
        warehouse:
        - warehouseId:
          - 456
          - 256
          - 598
    GetOrderResponse:
      title: Get Order response
      properties:
        order:
          $ref: '#/components/schemas/Order'
      allOf:
      - $ref: '#/components/schemas/CommonResponse'
      - type: object
    GetproductavailabilityResponse:
      title: GetProductAvailability response
      properties:
        availableStock:
          $ref: '#/components/schemas/ProductAvailabilityRes'
      allOf:
      - $ref: '#/components/schemas/CommonResponse'
      - type: object
    EetTaxRange_inner:
      type: object
      properties:
        taxRange:
          type: number
          description: VAT range, for free of VAT -1, 0 for standard ...etc.
          example: -1
        taxRate:
          type: number
          description: Real tax rate 0, 21, 15 ...
          example: 21
        amountInRate:
          type: number
          description: Tax basement in the range.
          example: 21
